apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: webapp
spec:
  host: webapp.example.com
  upstreams:
    - name: webapp
      service: webapp-svc
      port: 80
  routes:
    - path: /
      policies:
        - name: dos-policy
          apiGroup: appprotectdos.f5.com/v1beta1
          kind: DosProtectedResources
      action:
        pass: webapp